---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: fastdb-resspect-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-fastdb-resspect-test-shell
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[]]'
        nersc.gov/collab_uids: "99895"
        nersc.gov/gid: "95089"
        nersc.gov/gids: 60152,57177,95089,96414,99895
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-fastdb-resspect-test-shell
    spec:
      affinity: {}
      containers:
      - name: shell
        image: registry.nersc.gov/m1727/raknop/fastdb-shell:resspect-test
        env:
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_DBNAME
          value: brokeralert
        - name: MONGODB_COLLECTION
          value: alerts
        - name: MONGODB_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: mongodb_admin
              name: secrets
              optional: false
        - name: MONGODB_ADMIN_PASSWD
          valueFrom:
            secretKeyRef:
              key: mongodb_admin_passwd
              name: secrets
              optional: false
        - name: MONGODB_ALERT_WRITER_USER
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_writer
              name: secrets
              optional: false
        - name: MONGODB_ALERT_WRITER_PASSWD
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_writer_password
              name: secrets
              optional: false
        - name: MONGODB_ALERT_READER_USER
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_reader
              name: secrets
              optional: false
        - name: MONGODB_ALERT_READER_PASSWD
          valueFrom:
            secretKeyRef:
              key: mongodb_alert_reader_password
              name: secrets
              optional: false
        imagePullPolicy: Always
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 95089
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /secrets
          name: secrets
        - mountPath: /fastdb
          name: fastdb-install
        - mountPath: /query_results
          name: fastdb-query-results
        - mountPath: /sessions
          name: fastdb-sessions
        - mountPath: /sample
          name: fastdb-sample
        - mountPath: /code
          name: fastdb-checkout
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 57177
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: registry-nersc
      volumes:
      - name: secrets
        secret:
          defaultMode: 292
          optional: false
          secretName: secrets
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/resspect_test/install
          type: Directory
        name: fastdb-install
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/resspect_test/FASTDB
          type: Directory
        name: fastdb-checkout
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/resspect_test/query_results
          type: Directory
        name: fastdb-query-results
      - hostPath:
          path: /global/cfs/cdirs/lsst/groups/TD/SOFTWARE/fastdb_deployment/resspect_test/sessions
          type: Directory
        name: fastdb-sessions
      - hostPath:
          path: /global/cfs/cdirs/desc-td/ELASTICC2
          type: Directory
        name: fastdb-sample
---
apiVersion: v1
kind: Service
metadata:
  name: shell
  namespace: fastdb-resspect-test
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-fastdb-resspect-test-shell
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
